In [1]:
import pandas as pd

In [16]:
f = "../data/esolmet.txt"            #Editando con notepad++ se sustituyo ", " por " ", usando este ultimo como separador
esolmet = pd.read_csv(f,sep=" ",     #Después, se sustituyó "," por "" para evitar que se reconozcan como objetos
                      index_col=0,
                      parse_dates=True)     
esolmet.sort_index(inplace = True)
esolmet

,I_dir [W/m2],I_glo[W/m2],I_dif[W/m2],Iglo_inc[W/m2],Indice_UV[W/m2],Indice_UVA[W/m2],AirTC[°C],HR[%],WS[m/s],WD[grados],PB[mbar],Rain[mm]
Timestamp,,,,,,,,,,,,
2024-08-30 23:10:00,0.01,0.0,0.0,0.0,0.00,0.00,22.29,93.60,1.54,331.20,865.12,0.0
2024-08-30 23:20:00,0.06,0.0,0.0,0.0,0.00,0.00,22.42,92.00,1.46,330.40,865.21,0.0
2024-08-30 23:30:00,0.02,0.0,0.0,0.0,0.00,0.00,22.53,91.60,0.85,326.60,865.15,0.0
2024-08-30 23:40:00,0.03,0.0,0.0,0.0,0.00,0.00,22.56,91.30,1.01,339.80,865.13,0.0
2024-08-30 23:50:00,0.02,0.0,0.0,0.0,0.00,0.00,22.49,92.70,0.56,347.20,865.29,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-05 10:10:00,421.80,780.8,355.6,782.8,0.12,46.87,26.41,73.18,0.88,1.54,865.19,0.0
2024-09-05 10:20:00,355.90,670.3,301.1,674.4,0.11,42.37,26.53,71.56,1.43,1.57,865.16,0.0
2024-09-05 10:30:00,451.40,802.0,341.2,803.0,0.13,48.76,26.89,68.30,0.63,1.57,865.11,0.0
2024-09-05 10:40:00,380.40,768.3,356.6,766.9,0.13,47.16,27.30,68.81,1.66,1.56,864.98,0.0
2024-09-05 10:50:00,24.30,357.0,273.2,356.2,0.08,26.48,26.53,70.91,1.24,1.56,864.98,0.1

In [17]:
esolmet.to_csv("../data/esolmetFORMATO.csv", index=True)  # Usa index=True si quieres incluir los índices en el CSV

In [19]:
esolmetF = pd.read_csv("../data/esolmetFORMATO.csv",      #Esto es para corrborar, pero aun asi, se tiene que volver a indicar el indice 
                       index_col=0, 
                       parse_dates=True )
esolmetF

,I_dir [W/m2],I_glo[W/m2],I_dif[W/m2],Iglo_inc[W/m2],Indice_UV[W/m2],Indice_UVA[W/m2],AirTC[°C],HR[%],WS[m/s],WD[grados],PB[mbar],Rain[mm]
Timestamp,,,,,,,,,,,,
2024-08-30 23:10:00,0.01,0.0,0.0,0.0,0.00,0.00,22.29,93.60,1.54,331.20,865.12,0.0
2024-08-30 23:20:00,0.06,0.0,0.0,0.0,0.00,0.00,22.42,92.00,1.46,330.40,865.21,0.0
2024-08-30 23:30:00,0.02,0.0,0.0,0.0,0.00,0.00,22.53,91.60,0.85,326.60,865.15,0.0
2024-08-30 23:40:00,0.03,0.0,0.0,0.0,0.00,0.00,22.56,91.30,1.01,339.80,865.13,0.0
2024-08-30 23:50:00,0.02,0.0,0.0,0.0,0.00,0.00,22.49,92.70,0.56,347.20,865.29,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-05 10:10:00,421.80,780.8,355.6,782.8,0.12,46.87,26.41,73.18,0.88,1.54,865.19,0.0
2024-09-05 10:20:00,355.90,670.3,301.1,674.4,0.11,42.37,26.53,71.56,1.43,1.57,865.16,0.0
2024-09-05 10:30:00,451.40,802.0,341.2,803.0,0.13,48.76,26.89,68.30,0.63,1.57,865.11,0.0
2024-09-05 10:40:00,380.40,768.3,356.6,766.9,0.13,47.16,27.30,68.81,1.66,1.56,864.98,0.0
2024-09-05 10:50:00,24.30,357.0,273.2,356.2,0.08,26.48,26.53,70.91,1.24,1.56,864.98,0.1